### ISSUE TITLE
rossum_3.15.0.exe corrupt

### ISSUE THREAD

**Issue by MarkFarmiloe** [rossumai/rossumctl#41]
[rossum_3.15.0.exe](https://github.com/rossumai/rossum/releases/download/v3.15.0/rossum_3.15.0.exe) is only 106kb down from 22.5mb. I suggest it didn't compile properly.

**Comment by evelyn9191** [comment]
Hi @MarkFarmiloe 
Sorry for the late reply. We don't have rossum 3.15.0 available anymore but we've just released a new version that should be fine even for Windows. Feel free to download it.
