### ISSUE TITLE
ImportError: cannot import name 'save_virtual_workbook' from 'openpyxl.writer.excel'

### ISSUE THREAD

**Issue by swu5068** [rossumai/rossumctl#42]
I encountered the error as topic when running Rossum CLI, which I think _save_virtual_workbook_ has been no longer available since openpyxl 3.1.x. To resolve this, I uninstalled openpyxl and did `pip3 install openpyxl==3.0.10` then issue disappeared.

**Comment by karelhusa** [comment]
Either fixing the openpyxl dependency is required (to a version <3.1) or a code upgrade for the recent openpyxl version.

**Comment by 0skarmp** [comment]
> I encountered the error as topic when running Rossum CLI, which I think _save_virtual_workbook_ has been no longer available since openpyxl 3.1.x. To resolve this, I uninstalled openpyxl and did `pip3 install openpyxl==3.0.10` then issue disappeared.

thanks , i change the version of openpyxl i just need for export data in xls
